#!/bin/sh

case "$1" in
  start)
	echo 648000 > /sys/devices/system/cpu/cpufreq/policy0/scaling_max_freq
	;;
  stop)
	;;
  restart|reload)
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
