#!/bin/sh
#
# Starts nomadnet
#
NAME=rns-echo
DAEMON=/usr/sbin/$NAME

[ -r /etc/default/$NAME ] && . /etc/default/$NAME

start() {
	printf "Starting $NAME: "
	start-stop-daemon -S -q -b --exec $DAEMON -- -s --config=/root/.reticulum
	echo "OK"
}
stop() {
	printf "Stopping $NAME: "
	killall $NAME
	echo "OK"
}
restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

