#!/bin/sh
#
# Starts nomadnet
#
NAME=rns-echo
DAEMON=/usr/sbin/$NAME
PIDFILE="/var/run/$NAME.pid"

[ -r /etc/default/rns ] && . /etc/default/rns

start() {
	printf "Starting $NAME: "
	start-stop-daemon -S -q -b -m -p $PIDFILE -c rns -x $DAEMON -- -s --config $RETICULUM_CONFIG
	echo "OK"
}
stop() {
	printf "Stopping $NAME: "
	start-stop-daemon -K -q -p "$PIDFILE"
	echo "OK"
}
restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

